### ISSUE TITLE
#HU-010-001 Página de cada libro

### ISSUE THREAD

**Issue by JuanPSuarez** [JuanPSuarez/TSDWA-ProyectoIntegrador#4]
- [x] Crear el archivo .html
- [x] Cargar la imagen del libro
- [x] Cargar los datos basicos como (Titulo, Autor, Precio) Editorial, Año de Publicación, 
- [x] Descripcion breve o sinopsis.

**Comment by CeleTru** [comment]
- [ ] El sistema cargará una página o pantalla que mostrará información detallada sobre el libro seleccionado.
- [ ] Los detalles del libro incluirán el título, autor, género, portada, sinopsis, precio, editorial, año de publicación y cualquier otra información relevante.
- [ ] Los usuarios podrán ver reseñas y calificaciones de otros compradores si están disponibles.
- [ ] Se proporcionarán opciones para agregar el libro a la lista de deseos o al carrito de compras desde esta pantalla.
- [ ] Los usuarios podrán ver opciones de formatos disponibles (por ejemplo, versión impresa, eBook) y seleccionar su preferencia si es aplicable.
- [ ] La página permitirá una navegación fácil para regresar a la lista de resultados de búsqueda o continuar explorando otros libros.
- [ ] Si el usuario decide realizar la compra, se proporcionarán instrucciones claras para completar la transacción.
