### ISSUE TITLE
#HU-XXX-001 Validar maximo y minimo Nombre y Apellido

### ISSUE THREAD

**Issue by JuanPSuarez** [JuanPSuarez/TSDWA-ProyectoIntegrador#80]
Esta tarea se completa:

Limitando al usuario con nombre y apellido.

Minimo: 8 Caracteres
Maximo: 32 caracteres

**Comment by pupaycleo** [comment]
Me asigne la tarea Validar máximo y mínimo  Nombre y Apellido
