### ISSUE TITLE
#HU-XXX-001 Backend: Crear base de datos

### ISSUE THREAD

**Issue by JuanPSuarez** [JuanPSuarez/TSDWA-ProyectoIntegrador#81]
Esta tarea se completa creando:

La base de datos (script)

**Comment by jorgelinasapp** [comment]
Nos asignamos la tarea: [#HU-XXX-001 Backend: Crear base de datos#81](https://github.com/JuanPSuarez/TSDWA-ProyectoIntegrador/issues/81)
